drop table if exists orders, employees, clients, products, events, registered_events, canceled_events;

CREATE TYPE if not exists ORDER_STATUS as ENUM ('REGISTERED', 'IN_PROGRESS', 'READY', 'CANCELED');

create table if not exists orders (
	id bigint generated by default as identity not null primary key,
    status order_status NOT NULL
);

create table if not exists employees (
	id bigint generated by default as identity not null primary key
);

create table if not exists clients (
	id bigint generated by default as identity not null primary key
);

create table if not exists products (
	id bigint generated by default as identity not null primary key,
	cost float not null
);

create table if not exists events (
	id bigint generated by default as identity not null primary key,
	created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	order_id integer references orders(id),
	employee_id integer references employees(id),
	client_id integer references clients(id)
	);

create table if not exists registered_events (
    id bigint not null references events(id),
	expected_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	product_id integer references products(id)
);

create table if not exists canceled_events (
	id bigint not null references events(id),
	cancel_reason varchar(150) not null
);